GET http://localhost:4000/leaderboard

###

POST http://localhost:4000/login
content-type: application/json

{
    "username": "shiva",
    "password": "123"
}

###
POST http://localhost:4000/createUser
Content-Type: application/json

{
    "username": "shiva",
    "password": "123"
}

###
POST http://localhost:4000/postHighscore/29bc1603-8a29-4278-8e96-360a5307b62f
Content-Type: application/json

{
    "username": "shiva",
    "highscore": 12
}