GET http://localhost:4000/leaderboard

###

POST http://localhost:4000/login
content-type: application/json

{
    "username": "GamerS",
    "password": "grandemilan1899"
}

###
POST http://localhost:4000/createUser
Content-Type: application/json

{
    "username": "GamerS",
    "password": "grandemilan1899"
}

###
POST http://localhost:4000/postHighscore/5dd7ea10-9b43-4d52-95a5-490f5792b4bc
Content-Type: application/json

{
    "username": "GamerS",
    "highscore": 60000
}